name: hamazh_auth
description: "hamazh News test"

publish_to: 'HamazhCLL'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.0

  animations: ^2.0.7
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  encrypt: ^5.0.3
  motion_toast: ^2.9.1
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  connection_notifier: ^2.0.1
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  webview_flutter: ^4.7.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/image/



